const PORT = 3034
export const API_URL = `http://localhost:${PORT}`

export const LIMIT = 3

export const PAGINATION_USER_REQUEST = 'PAGINATION_USER_REQUEST'
export const PAGINATION_USER_SUCCESS = 'PAGINATION_USER_SUCCESS'
export const PAGINATION_USER_FAILURE = 'PAGINATION_USER_FAILURE'

export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE'

export const SEARCH_PAGINATION_USER_REQUEST = 'SEARCH_PAGINATION_USER_REQUEST'
export const SEARCH_PAGINATION_USER_SUCCESS = 'SEARCH_PAGINATION_USER_SUCCESS'
export const SEARCH_PAGINATION_USER_FAILURE = 'SEARCH_PAGINATION_USER_FAILURE'

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE'

export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST'
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE'
